// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TiaTeresa.Models;

#nullable disable

namespace TiaTeresa.Migrations
{
    [DbContext(typeof(TiaTeresaContext))]
    partial class TiaTeresaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("TiaTeresa.Models.Geschichte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Deutsch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Spanisch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitelDeutsch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TitelSpanisch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Geschichte");
                });

            modelBuilder.Entity("TiaTeresa.Models.Vokabel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Deutsch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Spanisch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vokabel");
                });
#pragma warning restore 612, 618
        }
    }
}
